<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Gurobi130.NET">
      <HintPath>C:\gurobi1302\win64\bin\Gurobi130.NET.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
